meetalva/alva

index.html
* relative require from script-included js did not work before
* fix by using a top-level require stanza instead as per https://github.com/electron-userland/electron-compile/issues/60
=> Use require stanza instead of script[src=""]

src/lsg/patterns/element/index.tsx
=> feat(lsg): bigger click-area for open/close icon on page-element

package.json
=> fix(build): electron should now always find the correct js file

src/component/container/pattern_list.tsx
This PR fixes the unique key error for PatternListContainer. The key should be the on the wrapper, not the child and the PR just moves it up 👍 
```js
/Applications/Alva.app/Contents/Resources/app.asar/node_modules/fbjs/lib/warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop.
Check the render method of `PatternListContainer`. See https://fb.me/react-warning-keys for more information.
in PatternList (created by PatternListContainer)
in PatternListContainer (created by App)
in div (created by styled.div)
in styled.div (created by PatternsPane)
in PatternsPane (created by App)
in div (created by styled.div)
in styled.div (created by Styled(styled.div))
in Styled(styled.div)
in Unknown (created by App)
in div (created by styled.div)
in styled.div (created …
```
=> fix(component): Fix PatternListContainer unique key error

src/electron/electron.ts
This disables dragging interaction on the main window of the application, e.g. when
pulling files from onto the application.
Before this change the entire application was blanked. By preventing the resulting
navigation event this does not happen after this change
related to #177
=> fix: disable unhandled file dragging

src/electron/menu.ts
focusedWindow is of type BrowserWindow and was converted to type WebContents to be able to trigger toggleDevTools on it. The better way it to get webContents from focusedWindow and then call toggleDevTools
=> fix(menu): it is not possible to call toggleDevTools on browserWindow

src/lsg/patterns/panes/preview-pane/index.tsx
We have to do this to make sure that styled-components does not always create a new class for every resize event
=> fix(preview): use inline style for setting max-width of preview area

scripts/dist-preprocess.js
Get the latest designkit master from github when building a release instead of using the local one.
**Why:**
The latest release (`0.7.0`) includes a more or less broken version of designkit because it has its dependencies messed up which makes it unbuildable today. As far as I can see the version contained in `0.7.0` was never a master of `meetalva/designkit` but just a local version of whom evers machine while building the release.
This is now prevented to happen again 🎉!
=> build(scripts): get latest designkit master on build

src/electron/menu.ts
This change adopts the spreading of async-await to `menu.ts`.
* Remove callback usage
* Change positional arguments to more descriptive interface
* Simplify querySaveFilePath to queryPath
* Move control flow decision (selection vs. cancel => string | undefined) to click handlers
=> refactor: simplify querySaveFilePath to async queryPath

package-lock.json, package.json, src/export/sketch-exporter.ts
This PR switches back from the fork of html-sketchapp to the official NPM module, after the author has now released a new version.
=> chore: switch html-sketchapp dep back to brainly

.gitignore
This prevents `*.log` files generated by npm from ending up in the repo
=> chore: prevent log files from ending up in version control

src/component/container/property-list.tsx, src/store/styleguide/property/object-property.ts, src/styleguide/analyzer/typescript-react-analyzer/property-analyzer.ts
Object types have been expanded at creation time which means that the following code within a components prop type declarations would lead to an ifinite loop.
```
export interface FooProps {
test: string;
bar: BarProps;
}
export interface BarProps {
foo: FooProps;
}
```
Object properties will now be expanded at render time (only if the user expands them in the property pane).
=> fix(object-property): infinite loop on type recursion

package.json
Neither tslint.json nor tsconfig.json use ts-config as a base. Therefor the dependency can be removed.
If this gets merged #360 should be closed.
=> chore(deps): remove unused ts-config dependency

package.json
Hello people,
I'd like to split the start and watch npm scripts.
On Windows machines, watching often causes terminal hangs and forced restarts,
and for main-process debugging, watching doesn't help anyway.
I'd like to start without watching, while others may do with.
=> chore: split start and watch scripts

src/component/container/element-list.tsx, src/component/container/element-wrapper.tsx, src/lsg/patterns/element/index.tsx, src/store/command/element-location-command.ts, src/store/command/element-name-command.ts, src/store/page/page-element.ts, src/store/store.ts
This implements an edit mode for page elements in the tree view. 
* Click on the label of a selected item
* Hit enter when an item is selected
* Blur the element
* Select another element
* Hit enter
<details>
<summary>Screencast</summary>
</details>
Fixes #205
=> feat: rename page elements #205

src/lsg/patterns/floating-button/demo.tsx, src/lsg/patterns/floating-button/index.md, src/lsg/patterns/floating-button/index.tsx, src/lsg/patterns/floating-button/pattern.json, src/lsg/patterns/icons/demo.tsx, src/lsg/patterns/icons/index.tsx
This implements a floating button component commonly found in Material Design. 
Prepares a bigger PR that implements UI to add new pages (#24).
=> feat: add floating-button component

src/component/page-list/page-add-button.tsx, src/component/page-list/page-list-container.tsx, src/component/page-list/page-list-preview.tsx, src/component/page-list/page-tile-container.tsx, src/lsg/patterns/floating-button/index.tsx, src/lsg/patterns/preview-tile/demo.tsx, src/lsg/patterns/preview-tile/index.tsx, src/store/page/page-ref.ts, src/store/store.ts
Extend the page list view with a floating button that adds a new page to the list
* Appends page always at end of list
* Selects and focuses new page for editing 
---
Usefulness very limited via https://github.com/meetalva/alva/issues/387, let's tackle this next
Fixes #24 
<details>
<summary>Screencast</summary>
</details>
=> feat: allow users to add new pages

src/electron/create-menu.ts, src/electron/renderer.ts
=> fix: execute custom keyboard handlers when iframe has focus

package-lock.json, package.json, src/components/layout/index.tsx, src/components/panes/element-pane/index.tsx, src/components/panes/preview-pane/index.tsx, src/container/app.tsx, src/container/preview-pane-wrapper.tsx, src/electron/server.ts, src/model/types.ts, src/preview/preview-document.ts, src/preview/preview-renderer.tsx, src/preview/preview.tsx
This PR removes the preview resizing in favor of resizable sidebars. It is a first shot at #178, implementing the raw resizing functionality. 
Went with this implementation because I had to touch the preview pane while implementing a mirror iframe that will be used to measure drop zone sizes etc.
* Resizing of left sidebar to the right 
* Resizing of right sidebar to the left
* Possibility to toggle display of sidebars
* Persistence of sidebar width
* Prepares work on #449 
* Partially tackles #178 
<details>
<summary>Screencast</summary>
</details>
=> feat: make sidebars resizeable

src/model/pattern-library/builtins/text.ts
... so it’s easier to see the text element when it is added.
=> feat: set default value of built-in text component

src/electron/context-menus.ts, src/electron/renderer.tsx, src/store/view-store.ts
* Correctly paste inside a given element
* Correctly select the newly pasted element
* Disable "paste inside" if the current element does not accept children
=> fix: restore paste inside element

src/electron/main.ts, src/electron/renderer.tsx, src/message/message.ts, src/model/types.ts, src/preview/preview-renderer.tsx, src/preview/preview.tsx, src/store/view-store.ts
Fixes a bug where slots would not register correctly when the 
type of a children property can not be resolved by the typechecker.
* Assume `children` with any type are slots
* Allow `@slot` annotations
* Allow `@href` annotations
=> fix: relax check for slot props

src/container/element-list/element-container.tsx
Because it does not make that much sense if you can collapse your entire page.
=> fix: show collapse not on root elements

src/preview/preview-renderer.tsx, src/preview/preview.tsx
This fixes a bug where highlighting (both tree to preview and preview to tree) would not work correctly on first load. 
It also fixes the selection styling to not "look broken" when selecting elements with a height or width of 0.
=> fix: highlight correctly on first load

src/analyzer/typescript-react-analyzer/property-analyzer/property-analyzer.ts, src/model/pattern-property/enum-property.ts, src/model/types.ts
Number Enums were parsed as Strings. They are now parsed as numbers via parseInt.
The headline component from the designkit should now have working enums again.
Should be squashed into `fix: analyze number enums correctly`
=> fix(typescript-react-analyzer): analyze number enums correctly

src/electron/main.ts
Hello,
Thanks for all the effort you are putting in Alva and the given lightning talk at JSConf EU 2018.
I have been looking at Alva's code and realised there are some redundant listeners. So I thought I could contribute to it a little bit.
There is no open issue about this. So I hope it's not a problem that I am just trying to fix a thing I have found on my own without creating an issue here. 
The issue is; whenever a user closes and opens a window in Alva, listeners which are in `src/electron/main.ts` file were re-attached. Therefore, after closing & opening Alva window several times, the actions in listeners were executed as many as it's re-opened. Then if a user tries to open an existing Alva file, (s)he sees multiple "open file" dialog.
A screenshot when an existing Alva file is …
=> fix: remove redundant event listeners

src/electron/renderer.tsx
Aimed for #534, openings of an Alva file can be reverted with `undo`.
Therefore, I have removed `store.commit()` from `ServerMessageType.OpenFileResponse` and `ServerMessageType.CreateNewFileResponse` in order to ignore these kind of changes for history.
=> fix: stop committing openings of files in store

.vscode/launch.json
* Add a debugging launch task to `VSCode`
* Rename `Jest All` to `Run Tests`
=> chore: add launch item for jest debugging

package-lock.json, package.json, tsconfig.json
Explicitly configure stylelint integration with TypeScript and styled-components. Also disable the `unknown-properties` rule to allow Webkit-only properties without producing warnings.
=> chore: explicitly configure typescript-styled-plugin

src/electron/main.ts
Before, after opening the file open/save dialog you could click on the alva app in the background. That meant, that you had an opened file window in the background you couldn’t see any more.
This fix binds the file open/save dialog to the focussed window, so it is always on the top.
=> fix(electron): open file dialog always on top

src/electron/create-menu.ts
Should be squashed into `feat(export-sketch): add opening instructions`
=> feat(export-sketch): add opening instructions

src/container/element-drag-image.tsx, src/container/element-list/element-list.tsx, src/container/pattern-list/pattern-item-container.tsx, src/container/pattern-list/pattern-list-container.tsx
* Use the same drag image for drag operations from element and pattern list
* Use a React component to create the desired image.
<details>
<summary>Screencast</summary>
</details>
=> fix: unify drag image style and handling

src/electron/main.ts, src/electron/renderer.tsx
Aimed for #555, the first action cannot be undone.
This issue helped me understand how the history works in the store. :)
So.. I think we don't have to keep/commit every change in the store. Instead, to make the first action undo-able, I have committed the state whenever a file is opened/created. Because it allows us to know the previous state of the current file that we can go back. Besides that, I have stopped committing the state in `ServerMessageType.StartApp`. Because that was having a role in making #534 possible.
=> fix: make first action undo-able

package-lock.json, package.json, src/components/splash-screen/index.tsx, src/electron/main.ts, src/electron/renderer.tsx, src/message/message.ts, src/persistence/persistence.ts
Catches an file-opening error and lets the user know what happened.
Should be squashed into `feat: show error on unreadable .alva files`
=> feat: show error on unreadable .alva files

src/electron/main.ts
If the user tries to connect a library folder that does not work, we should give him a warning about that.
should be squashed into `feat: show error if library cannot be connected`
=> feat: show error if library cannot be connected

src/electron/create-menu.ts, src/store/view-store.ts
For easier page switches I added two shortcuts.
* Add shortcuts for next and previous page
=> feat: add shortcut to switch pages

src/components/bug-report/index.tsx, src/components/button/index.tsx, src/components/layout-switch/layout-switch.tsx, src/components/view-switch/index.tsx, src/container/chrome/chrome-container.tsx, src/container/chrome/chrome-switch.tsx
I have added `doubleClick` event along with `event.stopPropagation` to elements in `<Chrome />` not to trigger `<Chrome />`'s `doubleClick` event. This pull request should resolve issue #571.
=> fix: disable doubleClick for chrome elements

src/model/pattern-library/pattern-library.ts, src/model/project.ts
This fixes an issue where the builtin pattern library was duplicated in certain conditions. 
This was caused by `Project.addPatternLibrary` incorrectly changing the id of updated builtin pattern library instances and adding new entries to the `.libraries` map.
After this change the builting pattern library is kepts stable, so no new entries are added to the relevant data structure.
=> fix: keep builtin library ids stable

src/preview/preview.ts, src/server/create-preview-route.ts
Address a bug that caused the preview to fail rendering
of user-provided components directly after adding them
to a project.
This also derives the bundle script tags directly from the preview
instance of Project instead of applying script changes imperatively
for `MessageType.ChangePatternLibraries`.
=> fix: ensure component registry is in sync

src/preview/element-area.ts
Address a minor bug where `PreviewStore.highlightArea` would display with a width and height of 0, rendering as 2x2 px rect in the top left corner of the preview.
=> fix: prevent display of highlight area with height/width 0

package-lock.json, package.json, src/components/view-switch/index.tsx, src/container/chrome/chrome-container.tsx, src/electron/create-file-message-handler.ts, src/electron/create-main-menu/create-file-menu.ts, src/electron/create-main-menu/create-library-menu.ts, src/electron/create-server-message-handler.ts, src/electron/main.ts, src/electron/show-discard-dialog.ts, src/electron/start-app.ts, src/message/envelope.ts, src/message/message.ts, src/model/pattern-library/pattern-library.ts, src/model/project.ts, src/model/user-store-property/user-store-property.ts, src/persistence/persistence.ts, src/renderer/create-handlers.ts, src/renderer/create-notifiers.ts, src/renderer/message-handlers/index.ts, src/renderer/message-handlers/process-save.ts, src/sender/server.ts, src/store/view-store.ts, src/types/index.ts, src/types/persistence.ts, src/types/serialized-model.ts
This changes the basic behavior to ask for a save path on quit / window close / save for draft projects instead of asking up front. 
Draft projects are saved in the application support files when first created and marked as draft. When one of the following events occur for a draft project, the user is asked for a path to save to:
* `Cmd+S` (draft projects)
* `Cmd+Shift+S` (all projects)
* Any dialog schedules a save transaction
Additionally, when trying to close a window with a draft project active the user is asked wether the current project should be saved, discarded or the close canceled.
<details>
<summary>Dialog</summary>
</details>
=> feat: create projects without explicit path

src/components/element/element.tsx
Have a look at the right element pane border (is missing for the text element)
Before:
After:
=> fix: remove element border overlay

src/container/properties-switch.tsx
... so it’s more clear to users whats’s behind that tab.
=> fix: rename project settings to libraries

src/electron/create-app-message-handler.ts, src/message/message.ts, src/renderer/renderer.tsx
This adds a feature where a dev can create pdf screenshots of the Alva chrome via `window.screenshot`. 
This is useful for further conversions to SVG via `pdf2svg` as well as for bug reporting. Might be a good idea to power issue reporting with this later on?
=> feat: add `window.screenshot` for svg-convertible chrome screenshots

src/electron/main.ts, src/electron/start-app.ts
* changed the way how file open requests coming from the os layer are handled
* this is a hotfix for the distributed executables
* ignore error message 'use strict' popping up when opening alva from the dev setup. we need to refactor cli arg handling down the road to get rid of this error as it is caused by assuming that the first cli arg represents the file to open. this is only true in some cases.
Fixes #[Issue]
=> fix: open files via double-click & cli args

CONTRIBUTING.md
As reported in #631, I have updated the broken links with the possible most accurate ones. I have acted as "beta" board is the current sprint and roadmap is the backlog. But for the roadmap, I have updated the wording as well.
Fixes #631
=> docs: update broken important resources in CONTRIBUTING.md

src/container/page-list/page-list-container.tsx, src/model/page/page.ts, src/model/project.ts, src/store/view-store.ts
This fixes a number of bugs around page drag/drop.
1. Decided based on `DropState.next` vs `DropState.back` if the Page should be inserted after (`movePageAfter`) or before (`movePageBefore`). 
Implementing the case handling exposed another bug where dropping/dragging a page on itself was not handled. I changed it to not show the drop indicators in this case.
2. Remove `project.reArrangePagesIndex`, use `project.movePageTo` instead
3. Abstract `project.movePageAfter` to `project.movePageTo` to power `project.movePageAfter` and `project.movePageBefore`
4. Provide and use `getIndex` on `Page` to avoid intermediary states in `PageListContainer`. Only state in `PageListContainer` now is `draggedPage`.
=> fix: honor back/next state on page drops correctly

src/model/project.test.ts, src/model/project.ts, src/store/view-store.ts
Related to #644. 
Fixes bug where undo/redo would not work for page reordering operations.
=> fix: retain pageList during serde cycle #644

src/menu/file-menu.tsx
Cmd+N was broken on the Splashscreen, now it isn't
=> fix: make sure new file menu action works

src/adapters/electron-adapter/electron-adapter.test.ts, src/adapters/electron-adapter/electron-adapter.ts, src/adapters/electron-adapter/electron-main-menu.ts, src/bin/electron.ts, src/hosts/electron-host/electron-host.ts, src/matchers/open-file-request.ts, src/matchers/use-file-request.ts, src/matchers/use-file-response.ts, src/message/message.ts, src/sender/sender.ts, src/server/server.ts
Now you can double-click files on your Finder or Explorer and Alva opens them.
To do:
---
**Status**:
Mac: ✅ @marionebl 
Windows: ✅ @marionebl 
<details>
<summary>Steps</summary>
* 1. Be sure Alva is closed
* 2. Double-Click on an Alva file
* 3. See a new window open with project view
* 4. No splashscreen window opens
</details>
---
**Status**
Mac: ✅ @marionebl 
Windows: **not applicable**
<details>
<summary>Steps</summary>
* 1. Open Alva, so it shows the Splash Screen
* 2. Close the Splash Screen window
* 3. Double-Click on an Alva file
* 4. See a new window open with project view
* 5. No splashscreen window opens
</details>
---
**Status**
Mac: ✅ @marionebl 
Windows: ✅ @marionebl 
<details>
<summary>Steps</summary>
* 1. Open Alva, so it shows the Splash Screen
* 2. Double-Click on an …
=> fix: open files on doubleclick

src/adapters/electron-adapter/electron-adapter.ts, src/matchers/paste.ts
Status: ✅ @tilmx
<details>
1. Create new file
2. Add text element to first page
3. Select "Text" in text element's `text` property
4. Hit `cmd+c`, thenn `cmd+v` 
5. See "TextText" in property field and preview
</details>
---
Status: ✅ @tilmx  
<details>
1. Create new file
2. Add text element to first page
3. Select Element
4. Hit `cmd+c`
5. Focus text element 
6. Hit `cmd+v`
7. Nothing happens 💤 
</details>
---
Status: ✅ @tilmx 
<details>
1. Create new file
3. Select Element
4. Hit `cmd+c`
5. Open and focus development editor
6. Hit `cmd+v`
7. Nothing happens 💤 
</details>
---
Status: ✅ @tilmx 
<details>
1. Create new file
2. Open and focus development editor
3. Select some text in development editor
4. Hit `cmd+c` and `cmd+v`
7. Copied text is added at cursor position
</details>
---
=> fix: prevent pasting of alva models into property fields

README.md
* Add very on-the-nose links to our main entry points
* Shorten the introduction paragraph to the essentials
* Add a note about long-form guides
=> docs: be less handwavy #634

jest.config.js, src/model/project.ts, src/preview/preview-store.test.ts, src/preview/preview-store.ts, src/preview/test.ts
* `elementActions` can either receive a string containing the **action id** or an array containing several **action ids** to be executed.
1. Open a new Alva file
2. Connect the design kit
3. Drag the Input component into the element list
4. Click on the element list name
5. On the right sidebar choose **Handle Change**
5.1 Perform **Set Variable**
5.2 Give a name to your variable e.g. `da bomb` in the named field
5.3 Select **Payload > Value** in the **to** input field
5.4 Select `da bomb` on the **Value** field
6. Type some text in the component
[element-action-test.alva.zip](https://github.com/meetalva/alva/files/2667087/element-action-test.alva.zip)
=> fix: get and execute element actions

src/analyzer/react-utils/is-react-component-type.ts, src/bin/analyze.ts
This fixes a bug where Alva would ignore components that should be analyzed. This was caused by `@types/react` introducing a new intermediary `FunctionComponent` type that needed to be added to our explicit matching dictionary.
This also includes a preliminary `analyze` cli entry for easier testing of analyzer-related effects.
Discovered the issue while working on meetalva/designkit#55
=> fix: ensure compat with new react typing versions

.circleci/config.yml, packages/core/src/model/pattern-property/enum-property.test.ts, packages/core/src/model/pattern-property/enum-property.ts
Status: ✅ @tilmx   
<details>
1. Open Alva
2. Create new file
3. Connect the Design Kit
5. Start designkit build via `tsc -w`
6. Remove `Primary` enum member from `ButtonOrder`
7. Update the pattern library in Alva
8. Add a `Button` to the Element List
9. Only the `Secondary` option should be visible in the `order` select
</details>
=> chore: remove enum options when missing from updated property

.circleci/config.yml, .gitignore, .yarnclean, packages/core/package.json, packages/core/package.ncc.json, packages/core/src/bin/electron.ts, packages/core/src/preview/preview.ts, packages/core/src/server/routes/scripts.ts, packages/core/tsconfig.json, packages/core/webpack.config.js, packages/tools/alva-release.js, packages/tools/alva-trigger.js, yarn.lock
* Save weight in final apps by bundling main process stuff via ncc
* Build via `ncc` to `nccbuild`
* Operate `electron-builder`in `nccbuild`
* Introduce `package.ncc.json`, gets copied to `nccbuild`
=> perf: cut down on app weight by using ncc

packages/core/src/preview/preview-store.ts, packages/model/src/element/element-property/element-property.ts, packages/model/src/pattern/pattern-slot.ts
Instead of filling all props with coerced default values for props leave them undefined if possible (that is, if they are typed as optional)
=> fix: avoid filling in superfluous props

packages/analyzer/src/fixtures/prop-slots.tsx, packages/analyzer/src/react-utils/is-react-slot-type.test.ts, packages/analyzer/src/react-utils/is-react-slot-type.ts, packages/analyzer/src/test-utils.ts, packages/analyzer/src/typescript-utils/is-type-reference.ts, packages/analyzer/src/typescript-utils/is-union-type.ts
This widens what we accept as slot/children types:
```
export interface PropsWithSlots { 
reactNode: React.ReactNode;
reactNodeArray: React.ReactNode[];
explicitReactNodeArray: React.ReactNodeArray;
reactChild: React.ReactChild;
reactChildArray: React.ReactChild[];
reactElement: React.ReactElement<any>;
reactElementArray: React.ReactElement<any>[];
jsxElement: JSX.Element;
jsxElementArray: JSX.Element[];
union: React.ReactChild | React.ReactElement<any> | JSX.Element | string;
unionArray: (React.ReactChild | React.ReactElement<any> | JSX.Element | string)[];
}
```
=> fix: widen slot types

packages/components/src/drag-area/target-signal.tsx, packages/core/src/container/chrome/chrome-switch.tsx
Ensure correct zIndex for Chrome Switch (the switch used for showing/hiding panes on the top left), that you can click on 'Pages' without problems. 
Before that, there was an element with a higher zIndex, so clicking on 'Pages' didn't do anything.
=> fix: ensure correct zIndex for chrome switch

packages/components/src/add-button/index.tsx
Removed a second click handler on the same element, so there is only one page added (not two).
Fixes #784 
Fixes #779
=> fix: prevent duplicate pages

packages/core/src/container/splash-screen-container.tsx
Updated the get started link because the previous one was giving an error.
* Update the 'Get Started' link in splash screen
Fixes #[794](https://github.com/meetalva/alva/issues/794)
=> Update 'Get Started' link

packages/core/src/container/splash-screen-container.tsx
* spash screen getting started link was pointing to a non existent page which resulted in a 404
- n/a
n/a
=> fix(core): fix broken getting started link on splash screen
