- README.md
This will fix #40 
- Added a table of content
- beautify terminal commands
- replace `merge request` with `pull request`
- add styling to code examples
- restructure readme
> Feature beautify readme

- src/component/container/pattern_list.tsx
- src/lsg/patterns/pattern-list/index.tsx
- src/store/pattern/folder.ts
- src/store/pattern/parser/typescript_parser.ts
- src/store/pattern/pattern.ts
- src/store/store.ts
> feat: pattern icons

- src/component/container/pattern_list.tsx
convert pattern name to lowercase
> revert(component): fix(component): fix pattern list search

- .travis.yml
- lint-commits.sh
setting up travis for commitlint.
now commitlint will be run by travis - this will also check commit messages if you do them directly here at the github page
> chore(travis): add travis yml for commit message conventions

- CONTRIBUTING.md
- README.md
Please feel free to give as much feedback as possible + look at gramma etc. thx :)
Fix #86
>  docs(contributing): add contributing.md to help contributers

- package.json
> chore: run prettier when commiting

- src/lsg/patterns/panes/preview-pane/index.tsx
> fix(lsg): apply preview styling on webview element

- src/component/app.tsx
This PR addresses undesired app zoomig, mentioned in #89 
Based on this discussion int he electron repo: https://github.com/electron/electron/issues/3609
Not fully sure if this is the best place in the code to put those configs.
Point me in the right direction if you know better ;)
> fix(component): prevent app zooming

- src/electron/auto-updater.ts
see above
Please accept to fix my mess
> fix(auto-updater): correct value for progress bar and reset progress bar

- src/component/app.tsx
Pull down decision making into actual render differences to improve readability.
> refactor: simplify render method of <App/>

- package.json
> chore: update to electron v1.7.10

- src/lsg/patterns/pattern-list/index.tsx
> fix: disable svg image dragging in <PatternList>

- src/store/pattern/folder.ts
- src/store/pattern/parser/typescript_parser.ts
- src/store/pattern/pattern.ts
- src/store/store.ts
Improved function names to reflect the purpose of the icon path store functions
> chore(store): icon path API

- README.md
> docs(readme): 2018 update

- src/component/presentation/preview.tsx
- src/store/page/page.ts
- src/store/page/page_element.ts
- src/store/pattern/folder.ts
- src/store/pattern/parser/pattern_parser.ts
- src/store/pattern/parser/typescript_parser.ts
- src/store/pattern/pattern.ts
- src/store/pattern/property/boolean_property.ts
- src/store/pattern/property/enum_property.ts
- src/store/pattern/property/number_array_property.ts
- src/store/pattern/property/number_property.ts
- src/store/pattern/property/object_property.ts
- src/store/pattern/property/pattern_property.ts
- src/store/pattern/property/property.ts
- src/store/pattern/property/string_array_property.ts
- src/store/pattern/property/string_property.ts
- src/store/pattern/text_pattern.ts
- src/store/project/page_ref.ts
- src/store/project/project.ts
Much more documentation for the Store API.
> docs: store API

- src/electron/menu.ts
> feat(menu): new menuitem that opens settings file in default application

- src/electron/menu.ts
> fix(menu): also close alva when all windows are hidden

- src/component/container/element_list.tsx
- src/component/container/element_wrapper.tsx
- src/electron/context-menus.ts
- src/lsg/patterns/element/index.tsx
- src/lsg/patterns/list/index.tsx
> feat(menu): add context menu for page elements

- src/component/app.tsx
- src/component/preview.tsx
Security fix: Thanks to @Suhas-Gaikwad for reporting and helping with this issue
> fix: disabled drag-and-drop from outside the application

- scripts/dist-preprocess.js
no magic here. Less code = less bugs ;)
> fix(release): remove use of unknown dependency

- src/component/presentation/preview.tsx
* refrain from using setState. let mobx handle internal state
* move highlight area calculation code out of render function
> refactor(component): use mobx for internal state

- src/electron/electron.ts
Set minimum app widnow size. Also try to get primary screen size and start app in whole screen mode.
#107
> feat(window): minimum app window size

- package.json
> fix(package): update smoothscroll-polyfill to version 0.4.3

- src/store/styleguide/typescript-react-analyzer/index.ts
This fixes pattern detection on windows
> fix(store): normalize pattern ids across platforms

- src/electron/menu.ts
this is to make sure that the resize of the preview is finished
> fix(png-export): longer wait time before screenshot

- renovate.json
The PRs from renovate should have a specific label, as the one from greenkeeper had.
This PR will add a 'renovate' label to each PR from renovate
> chore(system): add renovate label to PRs from renovate

- package-lock.json
- package.json
- src/electron/menu.ts
- src/electron/renderer/preview.ts
- src/export/pdf-exporter.ts
- src/export/png-exporter.ts
- src/export/sketch-exporter.ts
- src/lsg/patterns/icons/index.tsx
- src/styleguide/renderer/react/preview.tsx
- tsconfig.json
This is a pull request to add exporting of the current page to sketch or PDF.
This PR is not complete yet, as it depends on another module not publish to npm yet.
> feat: export to sketch and pdf

- src/lsg/patterns/icons/index.tsx
- src/lsg/patterns/property-items/asset-item/index.tsx
- src/lsg/patterns/property-items/boolean-item/index.tsx
- src/lsg/patterns/property-items/enum-item/index.tsx
- src/lsg/patterns/property-items/property-label.tsx
- src/lsg/patterns/property-items/string-item/index.tsx
Making the property pane and all the property types really cool.
> feat: update styling of property pane

- package-lock.json
- package.json
- src/container/app.tsx
- src/container/element-list/element-list.tsx
- src/container/element-list/element-wrapper.tsx
- src/electron/main.ts
- src/electron/renderer.ts
- src/electron/server.ts
- src/message/message.ts
- src/model/element/element-content.ts
- src/model/element/element.ts
- src/model/page/page.ts
- src/model/types.ts
- src/preview/highlight-area.ts
- src/preview/preview-renderer.tsx
- src/preview/preview.tsx
- src/preview/select-area.test.ts
- src/preview/select-area.ts
- src/store/view-store.ts
> feat: select elements from preview

- src/electron/create-menu.ts
Cmd/Ctrl+U to make it easier to update
> feat: add hotkey for library update

- src/analyzer/typescript-react-analyzer/property-analyzer/property-analyzer.ts
- src/analyzer/typescript-react-analyzer/slot-analzyer.ts
- src/analyzer/typescript-react-analyzer/typescript-react-analyzer.ts
- src/analyzer/typescript/react-utils.ts
- src/electron/renderer.tsx
- src/message/message.ts
- src/message/server.ts
- src/store/view-store.ts
* Allow `any` children props as slots (commonly happens for built Alva, needs investigation)
* Allow `@slot` annotation
* Allow `@href` annotation
> fix: relax the slot check for children prop

- src/components/chrome/index.tsx
- src/container/chrome/chrome-container.tsx
- src/electron/main.ts
- src/message/message.ts
To make it easier to maximize window when needed.
Inspired behaviour: macOS Maps App, Safari, Photos... basically most of the macOS apps.
> feat: maximize window on chrome doubleclick

- src/container/app.tsx
- src/electron/create-menu.ts
- src/store/view-store.ts
- src/types/types.ts
Via "View" you can show or hide the element pane or the property pane for a cleaner working space.
Should be squashed into `feat: add option to hide sidebars`
> feat: add option to hide sidebars

- src/electron/create-menu.ts
> style: fix tab indentation

- .vscode/extensions.json
- .vscode/settings.json
* Debugger for Chrome
* Jest
* TSLint
* EditorConfig for VS Code
* …
Fixes #[Issue]
> chore(dev): add the following to vscode recommended extensions

- package-lock.json
- package.json
- src/container/element-list/element-list.test.tsx
- src/container/element-list/element-list.tsx
> fix: un-highlight slots accordingly during drag & drop

- src/components/demo-container.tsx
- src/components/editable-title/demo.tsx
- src/components/empty-state/index.tsx
- src/components/headline/demo.tsx
- src/components/headline/index.tsx
- src/components/list/index.tsx
- src/components/property-box/index.tsx
- src/components/splash-screen/index.tsx
- src/components/teaser/index.tsx
- src/container/project-settings-container.tsx
- src/container/splash-screen-container.tsx
- src/container/view-splashscreen.tsx
Added some link to the meetalva guides. The link leads to an 404-page, because they are not published yet.
> feat: add guide link to splash screen

- src/electron/create-library-message-handler.ts
Small corrections for spelling mistakes that where visible in dialogs.
> fix: correct user visible spelling errors

- src/components/pattern-list/index.tsx
- src/components/property-item/property-label.tsx
- src/components/view-switch/index.tsx
- src/container/pattern-list/pattern-item-container.tsx
Add some tooltips to the UI:
* Component Name (bottom left list)
* Component Description
* Property Label
> feat: add missing tooltips

- src/preview-renderer/synthetic-text.tsx
> fix: prevent clicking between text lines #651

- packages/core/src/analyzer/react-utils/is-react-component-type.ts
- packages/core/src/analyzer/typescript-react-analyzer/property-analyzer/property-analyzer.ts
- packages/core/src/analyzer/typescript-react-analyzer/typescript-react-analyzer.ts
- packages/core/src/analyzer/typescript-utils/get-tsa-export.ts
- packages/core/src/analyzer/typescript-utils/typescript-type.ts
- packages/core/src/container/preview-pane-wrapper.tsx
- packages/core/src/preview/get-components.ts
- packages/core/src/preview/preview-store.ts
- yarn.lock
<details>
1.  Clone material-ui
```
https://github.com/mui-org/material-ui.git
cd material-ui
yarn
cd packages/material-ui
yarn run build
```
2. Add `alva:main` and `alva:typings` to `packages/material-ui/build/package.json`
```json
{
"alva:main": "./index.alva.js",
"alva:typings": "./index.d.ts",
}
```
3. Copy `packages/material-ui/build/index.es.js` to `packages/material-ui/build/index.alva.js`
and prefix all import with `./es/`
```
/** @license Material-UI v3.7.0
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*/
import * as colors from './es/colors';
export { colors };
export { createGenerateClassName, createMuiTheme, createStyles, jssPreset, MuiThemeProvider, withStyles, withTheme } from './es/styles'; …
```
> WIP: fix: establish material ui compat

- packages/core/src/container/element-list/element-list.test.tsx
> chore: simplify test setup

- packages/core/src/adapters/electron-adapter/electron-adapter.ts
- packages/core/src/adapters/electron-adapter/electron-main-menu.ts
- packages/core/src/menu/edit-menu.ts
- packages/core/src/model/project.ts
- packages/core/src/renderer/message-handlers/app-request.ts
Fixes a bug where Electron keybindings would not work sporadically.
> fix: simplify app menu mgmt

- packages/core/package.json
... so CircleCI is happy again.
> fix: remove build publishing

- packages/core/src/components/add-button/index.tsx
- packages/core/src/components/button-group/index.tsx
- packages/core/src/components/button/index.tsx
- packages/core/src/components/item/item.styles.ts
- packages/core/src/components/layout-switch/layout-switch.tsx
- packages/core/src/components/property-details/index.tsx
- packages/core/src/components/property-item-boolean/index.tsx
- packages/core/src/components/property-item-string/index.tsx
- packages/core/src/components/property-reference/index.tsx
- packages/core/src/components/search/index.tsx
- packages/core/src/components/splash-screen/splash-screen.styles.ts
- packages/core/src/components/view-switch/index.tsx
- packages/core/src/container/chrome/chrome-switch.tsx
- packages/core/src/container/preview-pane-wrapper.tsx
- packages/core/src/container/recent-files-list.tsx
- packages/core/src/container/splash-screen-view.tsx
- packages/core/src/hosts/electron-host/create-window.ts
- packages/core/src/hosts/local-data-host.ts
Lets add a hover state and restyle the items
> fix: update splash screen

- packages/core/package.json
- packages/core/src/adapters/electron-adapter/electron-adapter.test.ts
- packages/core/src/adapters/electron-adapter/electron-adapter.ts
- packages/core/src/adapters/electron-adapter/electron-updater.ts
- packages/core/src/bin/electron.ts
- packages/core/src/hosts/electron-host/electron-host.ts
- packages/core/src/hosts/local-data-host.ts
- packages/core/src/types/hosts.ts
- packages/core/src/types/updater.ts
- yarn.lock
Fixes a bug where the draft state of project files was not computed correctly.
> fix: determine if file is saved in app data path correctly on win32

- packages/core/src/menu/help-menu.ts
- packages/core/src/menu/view-menu.ts
* move dev tools to help (to not irritate users) and rename it to "Debug Tools"
* fix GitHub spelling error
* rename "Development Editor" to "Variables Editor"
> fix: update menu options

- packages/core/src/components/button/index.tsx
- packages/core/src/components/chrome/index.tsx
- packages/core/src/components/item/item.styles.ts
- packages/core/src/components/link/index.tsx
- packages/core/src/components/teaser/teaser.tsx
- packages/core/src/container/app.tsx
- packages/core/src/container/chrome/chrome-container.tsx
- packages/core/src/container/connect-pane-container.tsx
- packages/core/src/container/element-list/element-list.tsx
- packages/core/src/container/property-list/property-list.tsx
- packages/core/src/container/recent-files-list.tsx
- packages/core/src/container/splash-screen-container.tsx
- packages/core/src/container/splash-screen-view.tsx
- packages/core/src/hosts/electron-host/create-window.ts
- packages/core/src/hosts/local-data-host.ts
* remove file name from recent files
* add new icons for files & drafts
* remove chrome bar on splash screen
* add recent files title
* add recent files empty state
* add social icons on splash screen
* fix case sensitivity in copy texts
> feat: update splashscreen

- LICENSE
- README.md
- packages/core/package.json
> chore: hello 2019

- packages/core/src/components/property-input/index.tsx
- packages/core/src/components/property-item-number/property-item-number.tsx
- packages/core/src/components/property-item-string/index.tsx
- packages/core/src/container/property-list/property-item-number.tsx
* add a custom minor/major stepper to number properties
> feat: add custom stepper

- .vscode/launch.json
* Update the debug profiles for vscode
> chore: update vscode debug profiles

- packages/analyzer/src/typescript-react-analyzer/typescript-react-analyzer.ts
- packages/analyzer/src/typescript-utils/get-export-infos.ts
- packages/analyzer/src/typescript-utils/typescript-export.ts
- packages/components/src/pattern-list/index.tsx
- packages/core/src/container/pattern-list/pattern-list-container.tsx
- packages/core/src/container/property-list/property-list.test.tsx
- packages/model/src/element/element-content.ts
- packages/model/src/element/element.ts
- packages/model/src/pattern/pattern.ts
- packages/types/src/serialized-model.ts
* add grouping of elements
* open open-able elements by default
> feat: add option to group components

- packages/model/src/library-store-item.ts
- packages/model/src/library-store.ts
Ensure we do not needlessly fetch data from NPM on every render.
> fix: avoid excessive npm data fetching

- CONTRIBUTING.md
- docs/guides/create-library.md
- docs/guides/create-pattern.md
- docs/guides/create-properties.md
- docs/guides/library.md
- docs/references/library-requirements.md
- packages/model/src/library-store.ts
- packages/site/package.json
- packages/site/src/releases.tsx
- packages/site/src/site.tsx
- yarn.lock
> docs: update docs related to designkit

- CONTRIBUTING.md
- README.md
- docs/contributors/develop-alva.md
Update setup instructions for README and CONTRIBUTING.md
Fixes #752
> docs: update setup instructions

- packages/model/src/library-store.ts
- packages/model/src/pattern/pattern.ts
- packages/util/src/guess-name.ts
- packages/util/src/index.ts
Adds the video player library to the recommended libs
> feat: add video player library

- packages/components/src/library-box/library-box.tsx
- packages/components/src/link-icon/index.tsx
- packages/components/src/teaser/teaser.tsx
- packages/core/src/container/library-store-item-container.tsx
Fix some minor bugs that caused some red warnings in the console
> fix: remove unnecessary console warnings

- packages/model/src/library-store.ts
Adds `@meetalva/maps` as recommended library
> feat: add maps as recommended library

- packages/model/src/library-store.ts
Alva/Unsplash Repo:
https://github.com/meetalva/unsplash
> feat: add unsplash package to store

- docs/guides/create-library.md
> fixed wrong dependency reference

- docs/guides/essentials.md
Hi all!
This project is super cool and I'd like to help out where I can. I figured tweaking the documentation a little would be a good place to start.
* Fixes typo `yor`=>`your`
* Adjusts some sentences to read more smoothly
> Spelling & grammar tweaks

- packages/core/package.json
#778 meetalva/material-design#2
> fix: exclude webpack from nccbuild 

- packages/site/package.json
- yarn.lock
> WIP docs: restore mission video

- README.md
- packages/core/src/menu/help-menu.ts
- packages/site/src/site.tsx
Fixes the links to the docs.
Closes #794
> docs: set correct links to documentation

- packages/site/package.json
- packages/site/src/cookie-notice.tsx
- packages/site/src/site.tsx
- yarn.lock
Adds a cookie notice for the website that can be discarded.
> feat: add cookie notice

- docs/guides-dev/create-properties.md
* … Syntax issue on string 50, plus some minor formatting proposals
Fixes #[Issue]:  There is no related issue
> type: documentation docs(fix) good first issue 
